---
title: "Meeting Notes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Monies

Needs to be invoiced before 31st March.

Things desired:

- Global geolines (0.5 day; free)
- State choropleth (0.5 day, free)
- Counties choropleth (0.5 day, free)
- eventsObserver (1/2 day)
- general research data management support/consultanct and advice on visualisations (2 day)

4 days @ £430pd = £1720.

- Credit for the future (1 day)

5 days @ £430pd = £2150.

# 


# 16th Jan

## Choropleth of US only

## Include undated letters?

Make default unticked on both choroplth and journey lines

## Esri.WorldShaded.Relief

Use this for letter journies

## Dark grey for all except selected families

## Limit zooming out to one world on journey lines

Think of how to do that.....

## Families Tab

## Remove congressional districts from choropleth

## Add human readable names to the tooltips for choropleth with States and Counties

## Do a doable check of the numbers

# Next Meeting

https://github.com/thomasp85/tweenr



Make it